### ISSUE TITLE
'Vote for Custodians' formatting

### ISSUE THREAD

**Issue by jbuck84** [eosdac/eosdac-client#13]
Where it shows who i vote for on the right on this page is a bit funky. The 'x' to delete a vote covers the account name of the person i am voting for. It doesn't make UX impossible, but it's not pretty. Would be nice to allow more horizontal space for this section to move the 'x' from covering the account name.

**Comment by michaeljyeates** [comment]
Need to use a smaller breakpoint and make sure that the existing votes appear at the top
