### ISSUE TITLE
Telegram Link

### ISSUE THREAD

**Issue by jbuck84** [eosdac/eosdac-client#14]
Redirects to KROWN DAC tg channel, instead of eosdac

**Comment by str** [comment]
@jbuck84 Where? I can't find any telegram links

**Comment by str** [comment]
This was on a testing dac created with the Krown DAC Data. 

http://light.dev2.dacfactory.io

**Comment by str** [comment]
I've just saw and it's hardcoded in the default boilerplate. Where should it point to?

**Comment by str** [comment]
OK, it's not hardcoded in the boilerplate, but it's a flag in the dacdirectory. The homepage is what's on the boilerplate. Being able to modify link the in the boilerplate as well as in the dacdirectory, is a bit confusing. 

I suggest removing the homepage $dir.REF_* and set the actual links in the boilerplate. 

In any case, having some documentation would avoid this confusions. I suggest having a wiki for the documentation. (probably here: https://github.com/eosdac/eosdac-client/wiki)

@michaeljyeates can you help with your feedback please?

**Comment by str** [comment]
So, now I understand how this works. The boilerplate IS NOT different per DAC by default, so it will stay as a config in the DAC/chain
