### ISSUE TITLE
Improve candidateship forms

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-client#16]
![image](https://user-images.githubusercontent.com/344748/73358220-84361d80-4274-11ea-8a35-ac36551243ef.png)

- [x] right default value, from what the custodian asked for
- [x] the currency dropdown only shows the currency set in max-pay
- [x] in my candidateship page, add a button to update my payment
- [x] asset-input for single currencies should not be a dropdown
- [x] allow to ask payments other than EOS
- [x] do not allow to set a value above max
- [x] handle cases when the max-pay is in EOS, but payment is in another currency

**Comment by str** [comment]
@lukestokes should it be 0? Or should it be what is currently set by the user?

Usually on most "edit" forms, the current value is preset.

What is confusing is that I was expecting to find a way to edit my payment amount in "my Candidateship" page, not in my payments page.

**Comment by lukestokes** [comment]
Yes, default to your existing pay amount.

If no amount is set for that user, use 0.

**Comment by str** [comment]
- [ ] right default value, from what the custodian asked for
- [ ] do not allow to set a value above max
- [ ] if editing, and having the value pre-set above max (because max was updated), show an error and do not allow to submit until setting below max
- [ ] the currency dropdown only shows the currency set in max-pay

**Comment by str** [comment]
There is an error setting the payment in LIGHT

![image](https://user-images.githubusercontent.com/123817/78521417-023c0680-7787-11ea-87b2-2ae18138c196.png)
