### ISSUE TITLE
Wildcard HTTPS cert

### ISSUE THREAD

**Issue by str** [eosdac/eosdac-client#24]
we will get a wildcard ssl certificate before launch

https://medium.com/@saurabh6790/generate-wildcard-ssl-certificate-using-lets-encrypt-certbot-273e432794d7

**Comment by lukestokes** [comment]
I think we should get one now since we're essentially using it for eosdac, krown, and others. I think EOS Foundation may need it also.

**Comment by michaeljyeates** [comment]
https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578

**Comment by str** [comment]
Cert not working for a dac I was testing at 

https://prueba1.dev3.dacfactory.io/

**Comment by str** [comment]
fixed
