### ISSUE TITLE
Member status in dropdown incorrect

### ISSUE THREAD

**Issue by michaeljyeates** [eosdac/eosdac-client#9]
The member status in the top menu dropdown always says non-member

**Comment by michaeljyeates** [comment]
Need to wait for mainnet replay before looking at this

**Comment by lukestokes** [comment]
Same on profile page

![image](https://user-images.githubusercontent.com/344748/73395475-fda23000-42b5-11ea-9c79-c325c82d2f55.png)

**Comment by str** [comment]
![image](https://user-images.githubusercontent.com/123817/76271329-c83a1c00-623d-11ea-93fc-dba4bd07a2e5.png)

Setting the user's profile calls `dacelections::stprofile` which does not seem to store any data, based on the block explorer's RAM consumed report.

**Comment by str** [comment]
NM, I now understand it's stored in the API, not the the chain.

**Comment by str** [comment]
I was not able to find any call to the API to store the profile. 

Please advice.

**Comment by michaeljyeates** [comment]
The API processor will store all actions to the mongo database, then the API reads the actions directly here

https://github.com/eosdac/eosdac-api/blob/master/api-handlers/getProfile.js#L42

**Comment by str** [comment]
So, the different calls I made to the API, they all return type=0.  It seems to be the issue is in the API.
